### ISSUE TITLE
00:00:00:00 format is not enforced... i.e 00:00:7:21 

### ISSUE THREAD

**Issue by mpaccione** [savalanpour/react-component-countdown-timer#5]
Looking at this image you can see there is no 0 added when the values are single digits. This is not a desired behavior for many people. Can a boolean attribute be put in to fix this?

![image](https://user-images.githubusercontent.com/8552642/78173416-95cea980-740c-11ea-91cf-a4952336d66a.png)

**Comment by savalanpour** [comment]
@mpaccione Thanks, specially for example.
Problem is solved.
