### ISSUE TITLE
Doesn't support ID Tag

### ISSUE THREAD

**Issue by mpaccione** [savalanpour/react-component-countdown-timer#7]
`<CountdownTimer id="end-countdown" count={moment().diff(blitz.active[0].endDate, 'seconds')} />
`
results in

`<div class="root-react-component-countdown-timer ">`

**Comment by savalanpour** [comment]
Ok, this should have been fixed by commit 36f90052b46496b35cde201395a9ea6c7d9992b1

Update to 0.1.7

Let me know if it works
